name = "taskflow-api"
main = "src/worker.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-04-15"

[env.production]
name = "taskflow-api-prod"

[env.staging]
name = "taskflow-api-staging"

# Preview/deploy from local without env specific config

[vars]
NODE_ENV = "production"
BACKEND_URL = "https://taskflow-api.yashsahu.workers.dev"
CLOUDFLARE_WORKER = "true"